SELECT

    CUSTOMER_ID,

    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,

    SUM(QUANTITY) AS TOTAL_QUANTITY,

    SUM(TOTAL_AMOUNT) AS TOTAL_SALES,

    AVG(TOTAL_AMOUNT) AS AVG_ORDER_VALUE

FROM {{ ref('fct_orders') }}

GROUP BY CUSTOMER_ID